<?php

// This file is programmatically generated by _blocks.acf using
// what it finds in the /core/, /private/ and /custom/ folders.

display_blocks();

function display_blocks($id='', $blocks=false) {

	if (have_rows('content_blocks', $id)):
		while (have_rows('content_blocks', $id)) : the_row();

			$themedir = get_template_directory();
			$sprpath = $GLOBALS['springboard_path'];
			$block = get_row(true);
			$layout = get_row_layout();
			$block['__index'] = get_row_index();

			// presumably old functionality to force the display of global blocks
			// through the display_blocks() function!!!
			if ($blocks) {
				$displayblock = false;
				if (in_array(get_row_index(), $blocks)) {
					$displayblock = true;
				}
			} else {
				$displayblock = true;
			}

			if ($displayblock) {

				// ======================================= //
				//           MILD (CORE) BLOCKS            //
				// ======================================= //
				
				if ($layout == 'block_accordion'):
					get_template_part('partials/core/mild/block_accordion/block_accordion', null, $block);
				elseif ($layout == 'block_anchor'):
					get_template_part('partials/core/mild/block_anchor/block_anchor', null, $block);
				elseif ($layout == 'block_bio'):
					get_template_part('partials/core/mild/block_bio/block_bio', null, $block);
				elseif ($layout == 'block_buttons'):
					get_template_part('partials/core/mild/block_buttons/block_buttons', null, $block);
				elseif ($layout == 'block_contactform'):
					get_template_part('partials/core/mild/block_contactform/block_contactform', null, $block);
				elseif ($layout == 'block_fullimage'):
					get_template_part('partials/core/mild/block_fullimage/block_fullimage', null, $block);
				elseif ($layout == 'block_legal'):
					get_template_part('partials/core/mild/block_legal/block_legal', null, $block);
				elseif ($layout == 'block_peoplegrid'):
					get_template_part('partials/core/mild/block_peoplegrid/block_peoplegrid', null, $block);
				elseif ($layout == 'block_posts'):
					get_template_part('partials/core/mild/block_posts/block_posts', null, $block);
				elseif ($layout == 'block_published'):
					get_template_part('partials/core/mild/block_published/block_published', null, $block);
				elseif ($layout == 'block_pullquote'):
					get_template_part('partials/core/mild/block_pullquote/block_pullquote', null, $block);
				elseif ($layout == 'block_rule'):
					get_template_part('partials/core/mild/block_rule/block_rule', null, $block);
				elseif ($layout == 'block_share'):
					get_template_part('partials/core/mild/block_share/block_share', null, $block);
				elseif ($layout == 'block_strip'):
					get_template_part('partials/core/mild/block_strip/block_strip', null, $block);
				elseif ($layout == 'block_tabs'):
					get_template_part('partials/core/mild/block_tabs/block_tabs', null, $block);
				elseif ($layout == 'block_testimonials'):
					get_template_part('partials/core/mild/block_testimonials/block_testimonials', null, $block);
				elseif ($layout == 'block_text'):
					get_template_part('partials/core/mild/block_text/block_text', null, $block);
				elseif ($layout == 'block_textimage'):
					get_template_part('partials/core/mild/block_textimage/block_textimage', null, $block);
				elseif ($layout == 'block_tiles'):
					get_template_part('partials/core/mild/block_tiles/block_tiles', null, $block);
				endif;


				// ======================================= //
				//          MEDIUM (CORE) BLOCKS           //
				// ======================================= //
				
				if ($layout == 'block_audioplayer'):
					get_template_part('partials/core/medium/block_audioplayer/block_audioplayer', null, $block);
				elseif ($layout == 'block_gallery'):
					get_template_part('partials/core/medium/block_gallery/block_gallery', null, $block);
				elseif ($layout == 'block_layerslider'):
					get_template_part('partials/core/medium/block_layerslider/block_layerslider', null, $block);
				elseif ($layout == 'block_logogrid'):
					get_template_part('partials/core/medium/block_logogrid/block_logogrid', null, $block);
				elseif ($layout == 'block_photostrip'):
					get_template_part('partials/core/medium/block_photostrip/block_photostrip', null, $block);
				elseif ($layout == 'block_resources'):
					get_template_part('partials/core/medium/block_resources/block_resources', null, $block);
				elseif ($layout == 'block_ticker'):
					get_template_part('partials/core/medium/block_ticker/block_ticker', null, $block);
				endif;


				// ======================================= //
				//           SPICY (CORE) BLOCKS           //
				// ======================================= //
				
				if ($layout == 'block_map'):
					get_template_part('partials/core/spicy/block_map/block_map', null, $block);
				elseif ($layout == 'block_related'):
					get_template_part('partials/core/spicy/block_related/block_related', null, $block);
				endif;


				// ======================================= //
				//              CUSTOM BLOCKS              //
				// ======================================= //
				
				if ($layout == 'block_featuredpullquote'):
					get_template_part('partials/custom/block_featuredpullquote/block_featuredpullquote', null, $block);
				elseif ($layout == 'block_hero'):
					get_template_part('partials/custom/block_hero/block_hero', null, $block);
				elseif ($layout == 'block_section'):
					get_template_part('partials/custom/block_section/block_section', null, $block);
				elseif ($layout == 'block_storysidebar'):
					get_template_part('partials/custom/block_storysidebar/block_storysidebar', null, $block);
				elseif ($layout == 'block_training'):
					get_template_part('partials/custom/block_training/block_training', null, $block);
				endif;


				// ======================================= //
				//             PRIVATE BLOCKS              //
				// ======================================= //
				
				

				

			}

		endwhile;
	endif;
}
?>